### ISSUE TITLE
Make it work with Quartz 3.0.7 and Mongo DB Driver 2.7.2

### ISSUE THREAD

**Issue by cispiroglu** [glucaci/mongodb-quartz-net#14]
Make it work with Quartz 3.0.7 and Mongo DB Driver 2.7.2

**Comment by chrisdrobison** [comment]
Does it not already? The library is targeting 3.x and Mongo 2.4.x which should allow you to use those versions.

**Comment by cispiroglu** [comment]
Sure already working with current(3.0.4) versions. But when consolidate with latest version of quartz then 3.0.4 up to version 3.0.7 and throws 3.0.4 not found exception when registering with castle windsor. so make it work may be the not correct i just meant upgrade version.

**Comment by chrisdrobison** [comment]
Try setting up an assembly binding in your project to fix this issue.
