### ISSUE TITLE
The state of fired trigger is always executing and not removed from fired trigger collection

### ISSUE THREAD

**Issue by PNTrong** [glucaci/mongodb-quartz-net#16]
Hi Chris,

My server is running on multiple instances so I enabled clustering. 
My job is running every minute. It's almost working well when I deploy the server. But sometimes the trigger state of the job is blocked because the state of fired trigger is "executing" in the database and it is not removed after the trigger is fired. 
Could you please help me to list some reasons for this issue? 

This is my code, I program multi-threads so I'm not sure that the issue is from it.
```
public async Task Execute(IJobExecutionContext context)
		{
			var stopwatch = new Stopwatch();
			stopwatch.Start();

			_logger.Info($"Automation Job is run at {DateTime.UtcNow}");

			// Run automation event
			var automationEventThread = RunCampaignAutomationEvent();

			// Run reminder service
			var reminderNotificationThread = _reminderService.RunReminderNotification();

			// Push notification for mobile based on Start Time and Reminder Before value.
			var reminderPushNotificationThread = _reminderService.PushNotificationToAssignee();

			await Task.WhenAll(automationEventThread, reminderNotificationThread, reminderPushNotificationThread);

			stopwatch.Stop();

			_logger.Info("Time elapsed: {0}", stopwatch.Elapsed);
		}
```

**Comment by chrisdrobison** [comment]
The locking mechanism is very rudimentary. Have you tried running this using the built-in RDBMS storage of Quartz to see if it does the same thing? I remember reading at one point that 1 min jobs might be a little fast. Have you tried slowing it down to run less frequently?

**Comment by PNTrong** [comment]
I still don't use the built-in RDBMS storage of Quartz yet. Currently, I have scheduled 2 jobs.
job 1 is every minute, job 2 is daily at 00:00 AM. Job 2 is working good. For job 1, My Dev server is always encountered this, however, the Production server is not. I'm running parallel in this service `RunCampaignAutomationEvent()` when the job is executing. So maybe the issue is from the power of the machine. What do you think?

**Comment by NorekZ** [comment]
@PNTrong try v3.0.5, hopefully it was just fixed...

**Comment by glucaci** [comment]
It was fixed
