### ISSUE TITLE
Using mongoDB and Quartzmin - Problems with storing jobs in mongodb

### ISSUE THREAD

**Issue by xico002** [glucaci/mongodb-quartz-net#17]
Hi! I´m developing a Quartz WebApi in .net core 2.2. I´m having trouble the first time i run my service. Some of the jobs are stored in MongoDB. Some aren´t. And then sometimes the jobs don´t trigger. Or if I stop the service and try running the service with one more job scheduled the whole thing gets confused somehow and the job is not stored in MongoDb. I´m using chronSchedule btw.
If i run my service without a persistent jobStore everything works fine.

What am I missing?

**Comment by xico002** [comment]
Oh and mys schedule starts with both STandByMode and StartMode True...

**Comment by xico002** [comment]
I guess my mistake was i had thw Mongodb driver for .net installed in my projectand that was messing with my service. After removing the package everything worked fine. I tested my service several times. The only thing that wasn't perfect was when i added two jobs to my service the schedule get a bit confused but gets back on track after a minute or two

**Comment by xico002** [comment]
Still sometimes one or other job doesnt schedule. Maybe it's because of the cronschedule im putting. im putting jobs every minute.
 And i thought i needed the mongodb driver to make this work...

**Comment by chrisdrobison** [comment]
Have you tried this same kind of scheduling frequency with the ADO.NET stuff?

**Comment by xico002** [comment]
So I increased the cron schedules intervals and the schedule works much better. Sometimes it takes time to get started or the jobs dont show right away in quartzmin but it gets back on track after a minute or so. Answering your question I haven´t tried it yet to connect with ado.net databases.

**Comment by xico002** [comment]
But I think there's a problem with the IScheduleBuilder. If i use the code WithSchedule(cronScheduleBuilder) instead of a regular WithCronSchedule(cronSchedule), the schedule just doesnt work well. Maybe its the misfires configuration, I dont know...

**Comment by glucaci** [comment]
Do you still have the problem ?

**Comment by glucaci** [comment]
Please open another issue if still have the problem
