### ISSUE TITLE
Triggers removal

### ISSUE THREAD

**Issue by claudiuconstantin** [glucaci/mongodb-quartz-net#2]
Can you give more details about how db trigger removal works? I am encountering some scenarios where triggers shouldn't be removed (on scheduler shutdown/restart), but maybe there's something I'm missing.

**Comment by chrisdrobison** [comment]
I'm not as familiar with the Quartz internals for shutdown and restart.
This project is pure a job repository so there really aren't very many
smarts in it. I tried to follow the built-in implementation very closely.
Although, it is likely I made some mistakes along the way as I recently
found with #1. Could you provide a unit test eliciting the problem you are
seeing?

**Comment by chrisdrobison** [comment]
I'll close this one for now until more feedback is given.

**Comment by claudiuconstantin** [comment]
When I'll have some time I'll look again into this in order to better identify and describe the issue. I finally decided over sqlite jobstore for my particular case.
