### ISSUE TITLE
NotSupportedException in .NET 6 apps

### ISSUE THREAD

**Issue by michaelnero** [glucaci/mongodb-quartz-net#31]
Hello. I'm getting a `NotSupportedException` when using this package with a .NET 6 app. The exception is below:

```
NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
MongoDB.Driver.Core.Connections.BinaryConnection.SendMessagesAsync(IEnumerable<RequestMessage> messages, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)

JobPersistenceException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
Quartz.Spi.MongoDbJobStore.MongoDbJobStore.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger, CancellationToken cancellationToken)
```

The issue is in the `DefaultObjectSerializer` class that is used in a couple of places to serialize the job data map and some calendar data. From what I see in the code, it's not possible to opt out of the `BinaryFormatter` usages by specifying my own serializer for these types since they are registered with the MongoDb driver in `JobStoreClassMap`.

I don't want to disable this check for my entire project. So, an alternative approach is to use `BinaryWriter` and `BinaryReader` to manually serialize/deserialize data, but this would break existing apps since the serialize format would change. Happy to submit a PR if you can offer a suggestion.

**Comment by Logikoz** [comment]
up

**Comment by glucaci** [comment]
4.0.0-preview.2
