### ISSUE TITLE
TriggerRepository should ensure required indexes are created

### ISSUE THREAD

**Issue by ovidiupop88** [glucaci/mongodb-quartz-net#35]
On large collections (e.g. tens of thousands of triggers), queries which use sort ` SortBuilder.Ascending(trigger => trigger.NextFireTime),
                    SortBuilder.Descending(trigger => trigger.Priority)` will fail unless an index is created.

I can create a PR with the required change.

**Comment by glucaci** [comment]
released with `4.0.0-preview.2`
