### ISSUE TITLE
JobName Primary Key

### ISSUE THREAD

**Issue by Skimmenthal13** [glucaci/mongodb-quartz-net#6]
Hi,

When i try to add and schedule a job with name  already existing, i have this problem : 
Quartz throw correctly an exception but in the job collection i found two jobs with the same jobname.
This with sql server doesn't happen. because i think in sql server jobname is a PK.

Thank you!

**Comment by chrisdrobison** [comment]
You can have jobs with the same name as long as they are in a different group. This was modeled after how the SQL Server implementation does it. The primary key is a composite of instance name, name, and group.

**Comment by Skimmenthal13** [comment]
Thank you for reply!
I have analyzed my configuration and the problem consist in a my uncorrect configuration.
In your examples, driver is configured programmatically. In my implementation i configure the properties in a config file.

I suppose that problem was in InstanceID parameter.
This is my configuration : 
```
<quartz> 
    <add key="quartz.scheduler.instanceName" value="DefaultQuartzScheduler" />
    <add key="quartz.scheduler.instanceId" value="MyIstance" />
    <add key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="10" />
    <add key="quartz.threadPool.threadPriority" value="Normal" />
    <add key="quartz.jobStore.misfireThreshold" value="5000" />
    <add key="quartz.jobStore.type" value="Quartz.Spi.MongoDbJobStore.MongoDbJobStore, Quartz.Spi.MongoDbJobStore" />
    <add key="quartz.jobStore.collectionPrefix" value="quartz" />
    <add key="quartz.jobStore.connectionString" value="myConn" />
  </quartz>

```
Using this configuration i have found some strange behaviour. 
After your reply i have change this property :  `<add key="quartz.scheduler.instanceId" value="AUTO" />`
And i observe the istance id value (_id) in scheduler collection was change in "NON_CLUSTERED".
After this change my application have the same behaviour of SQLServer.
